apiVersion: batch/v1 
kind: Job
metadata:
  name: multi-completion-batch-job
spec:
  activeDeadlineSeconds: 500
  parallelism: 2
  completions: 5
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
      - name: main
        image: luksa/batch-job
      restartPolicy: OnFailure
